services:
  app:
    build:
      context: .
      dockerfile: docker-configs/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./php_custom.ini:/usr/local/etc/php/conf.d/php_custom.ini
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - laravel-db-data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  laravel-db-data:
    driver: local